package org.casinocoin.dice.model.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 04 16:03:58 CEST 2014
// ---------------------------------------------------------------------
public interface ActiveAvailableJackpotBetsView extends ViewObject {
    void setparamCoinaddress(String value);
}

