package org.casinocoin.dice.model.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 26 15:10:13 CEST 2014
// ---------------------------------------------------------------------
public interface ActiveAvailableBetsView extends ViewObject {
    void setparamCoinaddress(String value);
}

