package org.casinocoin.dice.model.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 28 11:08:37 CEST 2014
// ---------------------------------------------------------------------
public interface PlacedBetsView extends ViewObject {
    void setparamPbsId(Integer value);

}

