package org.casinocoin.dice.model.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 25 15:03:10 CEST 2014
// ---------------------------------------------------------------------
public interface SecretsView extends ViewObject {
    String getCurrentSecret();

    Integer getCurrentSecretId();
}

