package org.casinocoin.dice.model.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 19 15:15:47 CEST 2014
// ---------------------------------------------------------------------
public interface SettingsView extends ViewObject {
    String getServerInitComplete();

    void setServerInitComplete(String value);

    String getServerWalletAddress();

    void setServerWalletAddress(String value);

    Integer getConfirmations();

    void setConfirmations(Integer value);

    String getJackpotWalletAddress();

    void setJackpotWalletAddress(String value);

    String getJackpotValue();

    void setJackpotValue(String value);
}

