package org.casinocoin.dice.model.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 26 10:50:02 CEST 2014
// ---------------------------------------------------------------------
public interface TransactionsView extends ViewObject {
    void setparamTxId(String value);
}

