package org.casinocoin.dice.model;

import oracle.jbo.server.ViewObjectImpl;

import org.casinocoin.dice.model.common.ActiveAvailableJackpotBetsView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 04 16:03:32 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ActiveAvailableJackpotBetsViewImpl extends ViewObjectImpl implements ActiveAvailableJackpotBetsView {
    /**
     * This is the default constructor (do not remove).
     */
    public ActiveAvailableJackpotBetsViewImpl() {
    }

    /**
     * Returns the variable value for paramCoinaddress.
     * @return variable value for paramCoinaddress
     */
    public String getparamCoinaddress() {
        return (String) ensureVariableManager().getVariableValue("paramCoinaddress");
    }

    /**
     * Sets <code>value</code> for variable paramCoinaddress.
     * @param value value to bind as paramCoinaddress
     */
    public void setparamCoinaddress(String value) {
        ensureVariableManager().setVariableValue("paramCoinaddress", value);
    }
}

