package org.casinocoin.dice.model;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 19 16:02:41 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DiceAppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DiceAppModuleImpl() {
    }


    /**
     * Container's getter for SettingsView1.
     * @return SettingsView1
     */
    public SettingsViewImpl getSettingsView1() {
        return (SettingsViewImpl) findViewObject("SettingsView1");
    }

    /**
     * Container's getter for AvailableBetsView2.
     * @return AvailableBetsView2
     */
    public ViewObjectImpl getAvailableBetsView1() {
        return (ViewObjectImpl) findViewObject("AvailableBetsView1");
    }

    /**
     * Container's getter for PlacedBetsView1.
     * @return PlacedBetsView1
     */
    public PlacedBetsViewImpl getPlacedBetsView1() {
        return (PlacedBetsViewImpl) findViewObject("PlacedBetsView1");
    }

    /**
     * Container's getter for SecretsView1.
     * @return SecretsView1
     */
    public SecretsViewImpl getSecretsView1() {
        return (SecretsViewImpl) findViewObject("SecretsView1");
    }

    /**
     * Container's getter for TransactionsView1.
     * @return TransactionsView1
     */
    public TransactionsViewImpl getTransactionsView1() {
        return (TransactionsViewImpl) findViewObject("TransactionsView1");
    }

    /**
     * Container's getter for ActiveAvailableBetsView1.
     * @return ActiveAvailableBetsView1
     */
    public ActiveAvailableBetsViewImpl getActiveAvailableBetsView1() {
        return (ActiveAvailableBetsViewImpl) findViewObject("ActiveAvailableBetsView1");
    }


    /**
     * Container's getter for TransactionsView2.
     * @return TransactionsView2
     */
    public TransactionsViewImpl getTransactionsView2() {
        return (TransactionsViewImpl) findViewObject("TransactionsView2");
    }

    /**
     * Container's getter for PbsToTtsViewLink1.
     * @return PbsToTtsViewLink1
     */
    public ViewLinkImpl getPbsToTtsViewLink1() {
        return (ViewLinkImpl) findViewLink("PbsToTtsViewLink1");
    }

    /**
     * Container's getter for AvailableBetsView2.
     * @return AvailableBetsView2
     */
    public ViewObjectImpl getAvailableBetsView2() {
        return (ViewObjectImpl) findViewObject("AvailableBetsView2");
    }

    /**
     * Container's getter for PbsToAbsViewLink1.
     * @return PbsToAbsViewLink1
     */
    public ViewLinkImpl getPbsToAbsViewLink1() {
        return (ViewLinkImpl) findViewLink("PbsToAbsViewLink1");
    }

    /**
     * Container's getter for ActiveAvailableJackpotBetsView1.
     * @return ActiveAvailableJackpotBetsView1
     */
    public ActiveAvailableJackpotBetsViewImpl getActiveAvailableJackpotBetsView1() {
        return (ActiveAvailableJackpotBetsViewImpl) findViewObject("ActiveAvailableJackpotBetsView1");
    }

    /**
     * Container's getter for HistorySecretsView1.
     * @return HistorySecretsView1
     */
    public SecretsViewImpl getHistorySecretsView1() {
        return (SecretsViewImpl) findViewObject("HistorySecretsView1");
    }
}

