package org.casinocoin.dice.model;

import java.util.HashMap;

import java.util.Map;

import oracle.jbo.server.ViewObjectImpl;

import org.casinocoin.dice.model.common.PlacedBetsView;

import org.codehaus.groovy.runtime.InvokerHelper;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 28 11:08:25 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PlacedBetsViewImpl extends ViewObjectImpl implements PlacedBetsView {
    /**
     * This is the default constructor (do not remove).
     */
    public PlacedBetsViewImpl() {
    }

    /**
     * Returns the variable value for paramPbsId.
     * @return variable value for paramPbsId
     */
    public Integer getparamPbsId() {
        return (Integer) ensureVariableManager().getVariableValue("paramPbsId");
    }

    /**
     * Sets <code>value</code> for variable paramPbsId.
     * @param value value to bind as paramPbsId
     */
    public void setparamPbsId(Integer value) {
        ensureVariableManager().setVariableValue("paramPbsId", value);
    }
    
    private class AgrFuncHelper extends HashMap {
        private String funcName;

        public AgrFuncHelper(String funcName){
          super();
          this.funcName = funcName;  
        }

        public Object get(Object key){
          //Invoke private method
          //of our DefaultRowSet (sum,count,avg,min,max)
          //key is argument expression for the aggr funcion being called
          //sum("Salary")

          return InvokerHelper.invokeMethod(getDefaultRowSet(), funcName, key);
        }
    }
    
    public Map getSum(){
        return new AgrFuncHelper("sum");
    }
      
    public Map getCount(){
        return new AgrFuncHelper("count");
    }
    
    public Map getMax(){
        return new AgrFuncHelper("max");
    }
}

