package org.casinocoin.dice.model;

import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;

import org.casinocoin.dice.model.common.SettingsView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 19 15:09:44 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SettingsViewImpl extends ViewObjectImpl implements SettingsView {
    /**
     * This is the default constructor (do not remove).
     */
    public SettingsViewImpl() {
    }

    /**
     * Returns the variable value for paramName.
     * @return variable value for paramName
     */
    public String getparamName() {
        return (String) ensureVariableManager().getVariableValue("paramName");
    }

    /**
     * Sets <code>value</code> for variable paramName.
     * @param value value to bind as paramName
     */
    public void setparamName(String value) {
        ensureVariableManager().setVariableValue("paramName", value);
    }
    
    public String getServerInitComplete(){
        setparamName("init_complete");
        setApplyViewCriteriaName("getSettingForName");
        executeQuery();
        if(hasNext()){
            Row settingRow = next();
            return (String) settingRow.getAttribute("Value");
        } else {
            return "0";
        }
    }
    
    public void setServerInitComplete(String value){
        setparamName("init_complete");
        setApplyViewCriteriaName("getSettingForName");
        executeQuery();
        if(hasNext()){
            Row settingRow = next();
            settingRow.setAttribute("Value", value);
            getApplicationModule().getTransaction().commit();
        }
    }
    
    public String getServerWalletAddress(){
        setparamName("server_wallet_address");
        setApplyViewCriteriaName("getSettingForName");
        executeQuery();
        if(hasNext()){
            Row settingRow = next();
            return (String) settingRow.getAttribute("Value");
        } else {
            return "";
        }
    }
    
    public void setServerWalletAddress(String value){
        setparamName("server_wallet_address");
        setApplyViewCriteriaName("getSettingForName");
        executeQuery();
        if(hasNext()){
            Row settingRow = next();
            settingRow.setAttribute("Value", value);
            getApplicationModule().getTransaction().commit();
        }
    }

    public Integer getConfirmations(){
        setparamName("confirmations");
        setApplyViewCriteriaName("getSettingForName");
        executeQuery();
        if(hasNext()){
            Row settingRow = next();
            return Integer.valueOf((String)settingRow.getAttribute("Value"));
        } else {
            return new Integer(10);
        }
    }
    
    public void setConfirmations(Integer value){
        setparamName("confirmations");
        setApplyViewCriteriaName("getSettingForName");
        executeQuery();
        if(hasNext()){
            Row settingRow = next();
            settingRow.setAttribute("Value", value.toString());
            getApplicationModule().getTransaction().commit();
        }
    }
    
    public String getJackpotWalletAddress(){
        setparamName("jackpot_wallet_address");
        setApplyViewCriteriaName("getSettingForName");
        executeQuery();
        if(hasNext()){
            Row settingRow = next();
            return (String) settingRow.getAttribute("Value");
        } else {
            return "";
        }
    }
    
    public void setJackpotWalletAddress(String value){
        setparamName("jackpot_wallet_address");
        setApplyViewCriteriaName("getSettingForName");
        executeQuery();
        if(hasNext()){
            Row settingRow = next();
            settingRow.setAttribute("Value", value);
            getApplicationModule().getTransaction().commit();
        }
    }
    
    public String getJackpotValue(){
        setparamName("jackpot_value");
        setApplyViewCriteriaName("getSettingForName");
        executeQuery();
        if(hasNext()){
            Row settingRow = next();
            return (String) settingRow.getAttribute("Value");
        } else {
            return "";
        }
    }
    
    public void setJackpotValue(String value){
        setparamName("jackpot_value");
        setApplyViewCriteriaName("getSettingForName");
        executeQuery();
        if(hasNext()){
            Row settingRow = next();
            settingRow.setAttribute("Value", value);
            getApplicationModule().getTransaction().commit();
        }
    }
}

