package org.casinocoin.dice.model;

import oracle.jbo.server.ViewObjectImpl;

import org.casinocoin.dice.model.common.TransactionsView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 26 10:49:46 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TransactionsViewImpl extends ViewObjectImpl implements TransactionsView {
    /**
     * This is the default constructor (do not remove).
     */
    public TransactionsViewImpl() {
    }

    /**
     * Returns the variable value for paramTxId.
     * @return variable value for paramTxId
     */
    public String getparamTxId() {
        return (String) ensureVariableManager().getVariableValue("paramTxId");
    }

    /**
     * Sets <code>value</code> for variable paramTxId.
     * @param value value to bind as paramTxId
     */
    public void setparamTxId(String value) {
        ensureVariableManager().setVariableValue("paramTxId", value);
    }
}

